# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yaml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fde-capu <fde-capu@student.42sp.org.br>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/17 14:08:46 by fde-capu          #+#    #+#              #
#    Updated: 2022/11/29 08:44:58 by fde-capu         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: "2.5"

services:

  ftt_backend:
    container_name: ftt_backend
    volumes:
      - ./health_check.sh:/health_check.sh
      - ./app_backend:/app
    working_dir: /app
    build:
      context: app_backend
      dockerfile: ../Dockerfile_ftt_backend
    restart: unless-stopped
    ports:
      - 3490:3000
    networks:
      - samsara_net
    entrypoint: npm run start:dev && /health_check.sh node
#    env_file: ftt_backend.env
#   links:
#     - ftt_database:ftt_database

  ftt_frontend:
    container_name: ftt_frontend
    volumes:
      - ./health_check.sh:/health_check.sh
      - ./app_frontend:/app
    working_dir: /app
    build:
      context: app_frontend
      dockerfile: ../Dockerfile_ftt_frontend
    restart: unless-stopped
    ports:
      - 3491:3000
    networks:
      - samsara_net
    entrypoint: npm run start:dev && /health_check.sh node
#    env_file: ftt_frontend.env
#    expose: [3000]

#  ftt_database:
#    container_name: ftt_database
#    image: postgres:latest
#    volumes:
#      - ./health_check.sh:/health_check.sh
#    restart: unless-stopped
#    networks:
#      - samsara_net
#    expose: [3000]
#    env_file: ftt_database.env
#    entrypoint: /health_check.sh;

networks:
  samsara_net:
