version: "3.8"

networks:
  samsara_net:

volumes:
  database_data:
  backend_uploads_data:

services:
  database:
    container_name: database
    image: postgres:latest
    restart: unless-stopped
    healthcheck:
      test: 
        - "CMD-SHELL"
        - "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - samsara_net
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - samsara_net
    depends_on:
      database:
        condition: service_healthy

  backend:
    container_name: backend
    build:
      context: ./backend
      target: production
    restart: unless-stopped
    networks:
      - samsara_net
    ports:
      - 3000:3000
    volumes:
      - backend_uploads_data:/var/tmp/uploads
    env_file:
      - ./.env
    depends_on:
      database:
        condition: service_healthy

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: production
      args:
        BACKEND_ORIGIN: ${BACKEND_ORIGIN}
    restart: unless-stopped
    ports:
      - 4200:4200
    env_file:
      - ./.env
    depends_on:
      backend:
        condition: service_healthy
