version: "3.8"

networks:
  samsara_net:

services:

  database:
    image: postgres:latest
    restart: unless-stopped
    healthcheck:
      test: 
        - "CMD-SHELL"
        - "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - samsara_net
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    env_file:
      - ./.env

  backend:
    build:
      context: ./backend
      target: ${ENVIRONMENT:-production}
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    networks:
      - samsara_net
    volumes:
      - ./backend:/app
    ports:
      - 127.0.0.5:80:3000
    env_file:
      - ./.env

  frontend:
    build:
      context: ./frontend
      target: ${ENVIRONMENT:-production}
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend:/app
    ports:
      - 127.0.0.6:80:4200
    env_file:
      - ./.env
